# Generated by Django 5.0.7 on 2024-07-09 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(max_length=100, unique=True, verbose_name='کد پرسنلی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('contact_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('position', models.CharField(max_length=100, verbose_name='سمت')),
                ('work_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='گروه کاری')),
                ('delivered_device', models.CharField(max_length=100, verbose_name='دستگاه تحویلی')),
                ('avatar', models.ImageField(blank=True, default='avatars/default_avatar.png', upload_to='avatars/', verbose_name='تصویر اپراتور')),
            ],
        ),
        migrations.CreateModel(
            name='LoadReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بار')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ گزارش')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_reports', to='Operator_app.operator')),
            ],
        ),
        migrations.CreateModel(
            name='FailureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('failure_type', models.CharField(max_length=200, verbose_name='نوع خرابی')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ گزارش')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_reports', to='Operator_app.operator')),
            ],
        ),
    ]
