# Generated by Django 5.0.7 on 2024-07-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='کد دستگاه')),
                ('name', models.CharField(max_length=200, verbose_name='نام دستگاه')),
                ('type', models.CharField(choices=[('Carrier', 'حمل کننده'), ('Loader', 'بارکننده')], max_length=50, verbose_name='نوع دستگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, verbose_name='نوع خرابی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('reported_by', models.CharField(max_length=200, verbose_name='گزارش شده توسط')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان گزارش')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='Machine_app.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=200, verbose_name='اپراتور')),
                ('type', models.CharField(choices=[('Start', 'شروع بکار'), ('Stop', 'توقف')], max_length=50, verbose_name='نوع عملیات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان عملیات')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='Machine_app.machine')),
            ],
        ),
    ]
